In [1]:
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd

#Creamos las listas donde almacenaremos toda nuestra información:
ranking_list = []
albums_list = []
bands_list = []
release_list = []
album_score = []

for i in range(51):
    #Cargamos las diversas paginas web, una a una
    page = requests.get("https://www.besteveralbums.com/overall.php?o=&f=&fv=&orderby=-InfoRankScore&sortdir=asc&page=" + str(i))
    soup = BeautifulSoup(page.content, 'html.parser')
    
    # Guardamos la clasificacion de los albumes en el ranking
    albums_ranking = soup.find_all('span',class_= 'bigger')
    for album in albums_ranking:
        ranking_list.append(album.b.text)
        
    # Guardamos el nombre de los albumes  
    albums_name = soup.find_all('div',class_='chartstring chart-title-col')
    for album in albums_name:
        albums_list.append(album.a.text)
        
    # Guardamos los nombres de las bandas   
    bands_name = soup.find_all('div',class_='chart-title-col chartstring')
    for band in bands_name:
        bands_list.append(band.a.text)
        
    # Guardamos los años en que salieron los albumes
    metrics = soup.find_all('div',class_='chart-stats-metric')
    j = 0;
    for i in range(int(len(metrics)/8)):
        release_list.append(metrics[j].text)
        j = j + 8
        
    # Guardamos la puntuación del álbum
    metrics = soup.find_all('div',class_='chart-stats-metric')
    j = 6;
    for i in range(int(len(metrics)/8)):
        album_score.append(metrics[j].a.text)
        j = j + 8
    
    
#Limpiamos, lo poco que se puede, los datos obtenidos y los pasamos a un dataframe:

ranking_list = [re.sub(r'\.','', x) for x in ranking_list]
album_score = [x[0:2] for x in album_score]
albumsdf = pd.DataFrame({'Position': ranking_list,
                         'Score': album_score,
                        'Album': albums_list,
                        'Band': bands_list,
                        'Release Year': release_list,})
albumsdf.to_csv('albums_info.csv')
albumsdf

,Position,Score,Album,Band,Release Year
0,1,92,OK Computer,Radiohead,1997
1,2,92,The Dark Side Of The Moon,Pink Floyd,1973
2,3,92,Abbey Road,The Beatles,1969
3,4,91,Revolver,The Beatles,1966
4,5,91,Sgt. Pepper's Lonely Hearts Club Band,The Beatles,1967
...,...,...,...,...,...
495,496,77,Out Of Time,R.E.M.,1991
496,497,79,Pretty Hate Machine,Nine Inch Nails,1989
497,498,78,Out Of The Blue,Electric Light Orchestra,1977
498,499,81,For Your Pleasure,Roxy Music,1973
499,500,83,Giant Steps,John Coltrane,1960